# Name of the project
PROJECT_NAME = QUIZ_GAME

#Doxyfile folder
DOC = documentation

#All source code files
SRC = quiz.c\
src/quiz_operations.c

#All test source files
TEST_SRC = src/quiz_operations.c\
test/test_quiz_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = quiz.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Build: 
	gcc function1.c test_quiz.c unity/unity.c -Iunity
Run:
	./a.out	